version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  web:
    build: .
    volumes:
      - .:/rails_vue_app
      - gem_data:/usr/local/bundle
      - node_modules:/app/node_modules
    command: bundle exec foreman start -f Procfile.dev
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db
    environment: 
       APP_DATABASE_HOST: db
       APP_DATABASE_USERNAME: root
       APP_DATABASE_PASSWORD: pass
    tty: true
    stdin_open: true
volumes:
  mysql_data:
  gem_data:
  node_modules: