version: '3'
services:
  #db:
  #  image: mysql:8.0
  #  environment:
  #    MYSQL_ROOT_PASSWORD: 'pass'
  #    MYSQL_USER: 'root'
  #  ports:
  #    - "3306:3306"
  #  volumes:
  #    - mysql_data:/var/lib/mysql
  # command: --default-authentication-plugin=mysql_native_password
  web:
    build: .
    volumes:
      - .:/rails_vue_app
      - public-data:/rails_vue_app/public
      - tmp-data:/rails_vue_app/tmp
      - gem_data:/usr/local/bundle
      - node_modules:/app/node_modules
    command: bundle exec unicorn -p 3000 -E production -c /rails_vue_app/config/unicorn.conf.rb
    ports:
      - "3000:3000"
      - "3035:3035"
    #depends_on:
    # - db
    tty: true
    stdin_open: true
  nginx:
    build:
      context: ./nginx
    volumes:
      - public-data:/rails_vue_app/public
      - tmp-data:/rails_vue_app/tmp
    ports: 
      - 80:80
    depends_on: 
      - web
    #  - db  
volumes:
  #mysql_data:
  gem_data:
  node_modules:
  public-data:
  tmp-data: